const STORAGE_KEY = "fiveYearPlanBuilder_revised_v1";

const stepDefs = [
  { id:"welcome", label:"Start & Personal Goals", title:"Start My Plan" },
  { id:"vision", label:"My Five-Year Vision", title:"My Five-Year Vision" },
  { id:"strengths", label:"Strengths & Growth", title:"Strengths & Growth" },
  { id:"career", label:"Career & Training", title:"Career & Training" },
  { id:"year1", label:"Year 1", title:"Year 1" },
  { id:"year2", label:"Year 2", title:"Year 2" },
  { id:"year3", label:"Year 3", title:"Year 3" },
  { id:"year4", label:"Year 4", title:"Year 4" },
  { id:"year5", label:"Year 5", title:"Year 5" },
  { id:"review", label:"Build My Plan", title:"My Finished Plan" }
];

const emptyYear = () => ({
  educationChoices:[], educationText:"",
  workChoices:[], workText:"",
  moneyChoices:[], moneyText:"",
  livingChoices:[], livingText:"",
  transportChoices:[], transportText:"",
  roadblockChoices:[], roadblockText:"",
  solutionChoices:[], solutionText:"",
  personalGoalChoices:[], personalGoalText:"",
  yearImage:""
});

const defaults = {
  studentName:"", grade:"", gradYear:new Date().getFullYear()+1, supportLevel:"guided",
  style:"professional", outputLayout:"compact",
  headshot:"", dreamImage:"", careerImage:"",
  personalGoals:[], personalGoalsOther:"", personalGoalsWhy:"",
  visionChoices:[], visionWork:"", visionHome:"", visionMoney:"", visionSuccess:"",
  strengths:[], strengthsOther:"", strengthExample:"",
  growth:[], growthOther:"", growthFirst:"",
  careerAreas:[], careerAreasOther:"", careerChoice:"", careerWhy:"", training:"", trainingOther:"", trainingHelp:[], trainingHelpOther:"",
  years:Array.from({length:5}, emptyYear),
  personalGoalReview:{}, personalGoalReflection:""
};

let state;
try {
  const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
  state = Object.assign({}, defaults, saved);
  state.years = Array.from({length:5}, (_,i)=>Object.assign(emptyYear(), (saved.years||[])[i]||{}));
  state.personalGoalReview = saved.personalGoalReview || {};
} catch { state = structuredClone(defaults); }
let currentStep = 0;

const options = {
  personalGoals:["Have a pet","Travel somewhere new","Have a boyfriend, girlfriend, or significant other","Get married","Have a child or family","Make new friends","Spend more time with friends","Join a club, team, group, or community activity","Learn to play an instrument","Learn another language","Learn to cook","Improve my health or fitness","Volunteer","Develop a hobby","Become more confident","Become more independent","I am not sure yet"],
  vision:["Working full time","Working part time","Attending college","Attending trade or technical school","Completing a certificate program","Serving in the military","Completing an apprenticeship","Volunteering","Owning a business","Still exploring"],
  strengths:["Working with my hands","Working with words","Working with numbers","Working independently","Working with a team","Helping people","Working with children","Working with older adults","Paying attention to details","Being creative","Being dependable","Being patient","Being empathetic","Solving problems","Being flexible","Learning technology","Following directions","Staying organized","Taking responsibility"],
  growth:["Staying organized","Being patient","Feeling confident","Avoiding negative self-talk","Multitasking","Speaking politely when frustrated","Public speaking","Meeting new people","Saying no appropriately","Balancing work and personal life","Asking for help","Completing tasks on time","Accepting feedback","Managing anger","Staying motivated","Adjusting to changes","Making decisions","Managing money","Using transportation","Advocating for myself"],
  careerAreas:["Animals and agriculture","Art, design, and media","Business and office work","Computers and technology","Construction and skilled trades","Cooking and food service","Education and childcare","Healthcare","Hospitality and tourism","Human services","Law and public safety","Manufacturing","Mechanics and transportation","Science and the environment","Sports and recreation","I am still exploring"],
  training:["On-the-job training","Certificate program","Apprenticeship","Trade or technical school","Community college","Four-year university","Military training","No additional training","I do not know yet"],
  trainingHelp:["Completing applications","Financial aid","Choosing a program","Transportation","Disability services","Study skills","Tutoring","Visiting schools","Understanding admission requirements"],
  education:["College","Trade or technical school","Certificate program","Apprenticeship","Job training","Not attending school or training","Unsure"],
  work:["Searching for a job","Working part time","Working full time","Internship","Apprenticeship","Volunteering","Running a business","Focusing on education first","Unsure"],
  money:["Receive support from family","Earn some of my own money","Pay some of my expenses","Pay most of my expenses","Support myself independently","Unsure"],
  living:["With a parent or guardian","With another family member","College dorm","Apartment by myself","Apartment with a roommate","With a partner","Supported living","My own house","Unsure"],
  transport:["Drive myself","Family member","Friend or coworker","Public transportation","School transportation","Paratransit","Ride-share service","Bicycle","Walk","Unsure"],
  roadblock:["Transportation","Not enough money","Need more education or training","Difficulty finding a job","Anxiety or stress","Trouble staying organized","Need help with applications","Housing costs","Health needs","Family responsibilities","Making friends or finding social activities","Feeling uncomfortable in new social situations","Not knowing what to do next"],
  solution:["Ask family for support","Work with my teacher","Meet with a counselor","Contact vocational rehabilitation","Practice the skill","Save money","Find transportation","Use a calendar or reminders","Apply for accommodations","Find a job coach","Join a club, class, team, or community group","Practice conversation and social skills","Ask someone I trust to attend a new activity with me","Research other options"]
};

const yearThemes = [
  ["Building My Foundation","🌱"],["Growing My Skills","🧰"],["Gaining Experience","🚀"],["Preparing for My Career","🧭"],["Living My Plan","⭐"]
];

function esc(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}
function save(silent=false){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(!silent)flash("Progress saved.");}
function flash(msg){document.querySelector(".flash")?.remove();const d=document.createElement("div");d.className="flash";d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),1800);}
function getPath(path){return path.split(".").reduce((o,k)=>o?.[k],state);}
function setPath(path,val){const keys=path.split(".");let o=state;keys.slice(0,-1).forEach(k=>o=o[k]);o[keys.at(-1)]=val;}
function allWithOther(values, other){return [...(values||[]), ...(String(other||"").trim()?[String(other).trim()]:[])];}
function checkboxGroup(path, items, selected=[], otherPath=""){return `<div class="option-grid">${items.map(x=>`<label class="option"><input type="checkbox" data-array="${path}" value="${esc(x)}" ${selected.includes(x)?"checked":""}><span>${esc(x)}</span></label>`).join("")}</div>${otherPath?`<label class="other-box">Other<input data-field="${otherPath}" type="text" value="${esc(getPath(otherPath)||"")}" placeholder="Write another idea"></label>`:""}`;}
function radioGroup(path, items, selected="", otherPath=""){return `<div class="option-grid">${items.map(x=>`<label class="option"><input type="radio" name="${path}" data-field="${path}" value="${esc(x)}" ${selected===x?"checked":""}><span>${esc(x)}</span></label>`).join("")}</div>${otherPath?`<label class="other-box">Other<input data-field="${otherPath}" type="text" value="${esc(getPath(otherPath)||"")}" placeholder="Write another idea"></label>`:""}`;}
function writingBox(path,prompt,starters,value){const open=state.supportLevel==="supported"?"open":"";return `<label class="writing-label">${esc(prompt)}<textarea data-field="${path}" spellcheck="true" placeholder="Write in your own words...">${esc(value||"")}</textarea></label>${state.supportLevel!=="independent"?`<details class="sentence-help" ${open}><summary>Need help getting started?</summary><ul>${starters.map(s=>`<li>${esc(s)}</li>`).join("")}</ul></details>`:""}`;}
function imageUpload(path,label,value){return `<div class="image-upload"><div class="image-preview">${value?`<img src="${value}" alt="Uploaded image">`:`<span>📷</span><small>No picture selected</small>`}</div><div><label>${esc(label)}<input type="file" accept="image/*" data-image="${path}"></label><p class="help">Optional. Choose a school-appropriate photo or image.</p>${value?`<button type="button" class="secondary remove-image" data-image="${path}">Remove picture</button>`:""}</div></div>`;}

function renderNav(){const nav=document.getElementById("stepNav");nav.innerHTML=stepDefs.map((s,i)=>`<button class="nav-step ${i===currentStep?"active":""} ${i<currentStep?"done":""}" data-step="${i}"><span class="nav-num">${i+1}</span><span>${esc(s.label)}</span></button>`).join("");nav.querySelectorAll("[data-step]").forEach(b=>b.onclick=()=>{collect();currentStep=Number(b.dataset.step);render();});}

function renderWelcome(el){el.innerHTML=`<div class="hero"><div><span class="pill">Student-friendly • First person • Editable</span><h3>Let’s imagine your life five years from now.</h3><p>Answer short questions, choose ideas, and write a few sentences in your own words. Your answers will become a complete Five-Year Plan.</p></div><div class="hero-art"><div class="year-card y1">Year 1</div><div class="year-card y2">Year 3</div><div class="year-card y3">Year 5</div></div></div>
<div class="form-grid student-basics"><label class="basic-field name-field"><span class="field-label">👤 Your name</span><input data-field="studentName" value="${esc(state.studentName)}" placeholder="Example: Jordan"></label><label class="basic-field grade-field"><span class="field-label">🎓 Current grade</span><select data-field="grade"><option value="">Choose one</option>${[9,10,11,12].map(x=>`<option ${String(state.grade)===String(x)?"selected":""}>${x}</option>`).join("")}</select></label><label class="basic-field grad-year-field"><span class="field-label">📅 Expected graduation year</span><input data-field="gradYear" type="number" min="2026" max="2045" value="${esc(state.gradYear)}"></label><label class="basic-field support-field"><span class="field-label">✍️ Writing support</span><select data-field="supportLevel"><option value="independent" ${state.supportLevel==="independent"?"selected":""}>Independent Writer</option><option value="guided" ${state.supportLevel==="guided"?"selected":""}>Guided Writer</option><option value="supported" ${state.supportLevel==="supported"?"selected":""}>Highly Supported Writer</option></select></label></div>
<div class="question"><h3>📷 Add a picture of yourself</h3>${imageUpload("headshot","Upload a headshot or student photo",state.headshot)}</div>
<div class="question"><h3>My Personal and Social Goals</h3><p class="help">Choose anything you may want in your personal life. These are hopes, not requirements, and it is okay to be unsure.</p>${checkboxGroup("personalGoals",options.personalGoals,state.personalGoals,"personalGoalsOther")}<div style="margin-top:16px">${writingBox("personalGoalsWhy","Why are some of these goals important to you?",["One personal goal that matters to me is…","I would like to… because…","I am still deciding whether…"],state.personalGoalsWhy)}</div></div>
<div class="tip-box"><strong>There are no wrong answers.</strong> Your plans may change as you learn more about yourself.</div>`;}

function renderVision(el){el.innerHTML=`<p class="section-intro">Think about the life you hope to build. Choose ideas first, then write in your own words.</p><div class="question"><h3>What might you be doing?</h3>${checkboxGroup("visionChoices",options.vision,state.visionChoices,"visionOther")}</div><div class="question">${writingBox("visionWork","What do you hope to be doing for work, school, or training?",["Five years from now, I hope to…","I would like to work…","I may still be exploring…"],state.visionWork)}</div><div class="question">${writingBox("visionHome","Where do you hope to live, and what might your daily life be like?",["I hope to live…","At home, I want to…","I may live with…"],state.visionHome)}</div><div class="question">${writingBox("visionMoney","What do you hope to be able to pay for or save for?",["I hope to earn enough money to…","I want to save for…","I may need help learning to…"],state.visionMoney)}</div><div class="question">${writingBox("visionSuccess","What would make you feel successful?",["I will feel successful when…","Success to me means…","I will be proud if…"],state.visionSuccess)}</div><div class="question"><h3>Optional picture for My Dream</h3>${imageUpload("dreamImage","Upload a picture that represents your dream",state.dreamImage)}</div>`;}

function renderStrengths(el){const count=allWithOther(state.strengths,state.strengthsOther).length;el.innerHTML=`<p class="section-intro">Choose <strong class="highlight">FIVE strengths</strong> and up to five skills you want to improve.</p><div class="question"><h3>My Strengths <span class="count-pill">${count} of 5 selected</span></h3>${checkboxGroup("strengths",options.strengths,state.strengths,"strengthsOther")}</div><div class="question">${writingBox("strengthExample","Tell about a time you used one of your strengths.",["One strength I use is…","I showed this strength when…","This strength will help me because…"],state.strengthExample)}</div><div class="question"><h3>Skills I Want to Improve</h3>${checkboxGroup("growth",options.growth,state.growth,"growthOther")}</div><div class="question">${writingBox("growthFirst","Which skill would you like to work on first?",["I want to improve…","One step I can take is…","Someone who can help me is…"],state.growthFirst)}</div>`;}

function renderCareer(el){el.innerHTML=`<p class="section-intro">Explore work and training choices. It is okay if your career goal changes later.</p><div class="question"><h3>Career areas that interest me</h3>${checkboxGroup("careerAreas",options.careerAreas,state.careerAreas,"careerAreasOther")}</div><div class="question">${writingBox("careerChoice","What job or career would you like to explore?",["A career I want to explore is…","I may want to become…","I am interested in…"],state.careerChoice)}</div><div class="question">${writingBox("careerWhy","Why does this career interest you?",["This career interests me because…","I would enjoy…","This career matches my strength in…"],state.careerWhy)}</div><div class="question"><h3>Education or training I may need</h3>${radioGroup("training",options.training,state.training,"trainingOther")}</div><div class="question"><h3>Help I may need</h3>${checkboxGroup("trainingHelp",options.trainingHelp,state.trainingHelp,"trainingHelpOther")}</div><div class="question"><h3>Optional career picture</h3>${imageUpload("careerImage","Upload a picture connected to your career goal",state.careerImage)}</div>`;}

function renderYear(el,i){const y=state.years[i], [theme,icon]=yearThemes[i], year=Number(state.gradYear||new Date().getFullYear())+i;const base=`years.${i}`;el.innerHTML=`<div class="year-page year-tone-${i+1}"><div class="year-header"><div class="big-year">${i+1}</div><div><p class="year-kicker">${icon} YEAR ${i+1} OF 5</p><h3>${year} — ${theme}</h3><p>Describe what this year may look like. It is okay if your plan changes.</p></div></div>
<div class="question"><h3>🎓 Education and Training</h3>${checkboxGroup(`${base}.educationChoices`,options.education,y.educationChoices,`${base}.educationOther`)}${writingBox(`${base}.educationText`,`What do you hope to do for school or training during this year?`,["During this year, I plan to…","I may attend…","I want to learn…"],y.educationText)}</div>
<div class="question"><h3>💼 Employment</h3>${checkboxGroup(`${base}.workChoices`,options.work,y.workChoices,`${base}.workOther`)}${writingBox(`${base}.workText`,`What do you hope to do for work?`,["I hope to work…","I would like a job at…","This job interests me because…"],y.workText)}</div>
<div class="question"><h3>💰 Money</h3>${checkboxGroup(`${base}.moneyChoices`,options.money,y.moneyChoices,`${base}.moneyOther`)}${writingBox(`${base}.moneyText`,`What will you need to pay for or save money for?`,["I plan to save for…","I may need to pay for…","I want to learn how to budget for…"],y.moneyText)}</div>
<div class="question"><h3>🏠 Living Arrangements</h3>${checkboxGroup(`${base}.livingChoices`,options.living,y.livingChoices,`${base}.livingOther`)}${writingBox(`${base}.livingText`,`Where do you think you will live?`,["I think I will live…","At home, I will be responsible for…","I may need support with…"],y.livingText)}</div>
<div class="question"><h3>🚌 Transportation</h3>${checkboxGroup(`${base}.transportChoices`,options.transport,y.transportChoices,`${base}.transportOther`)}${writingBox(`${base}.transportText`,`How will you get to work, school, appointments, or activities?`,["I plan to get around by…","I want to learn how to…","Transportation may be easier if…"],y.transportText)}</div>
<div class="question"><h3>🚧 Possible Challenge</h3>${checkboxGroup(`${base}.roadblockChoices`,options.roadblock,y.roadblockChoices,`${base}.roadblockOther`)}${writingBox(`${base}.roadblockText`,`What might make this part of your plan difficult?`,["One challenge might be…","This could be difficult because…","I may need help with…"],y.roadblockText)}</div>
<div class="question"><h3>✅ My Possible Solution</h3>${checkboxGroup(`${base}.solutionChoices`,options.solution,y.solutionChoices,`${base}.solutionOther`)}${writingBox(`${base}.solutionText`,`What could you do, or who could help?`,["If this happens, I can…","I can ask… for help.","One solution could be…"],y.solutionText)}</div>
<div class="question"><h3>❤️ Personal Goal for This Year</h3><p class="help">Choose one or more of the personal goals from the beginning that you may work toward this year.</p>${checkboxGroup(`${base}.personalGoalChoices`,personalGoalsList(),y.personalGoalChoices,`${base}.personalGoalOther`)}${writingBox(`${base}.personalGoalText`,`What personal or social goal might you work toward this year?`,["This year, I hope to…","One personal goal I may work on is…","A small step I can take is…"],y.personalGoalText)}</div>
<div class="question"><h3>Optional picture for Year ${i+1}</h3>${imageUpload(`${base}.yearImage`,`Upload a picture that represents Year ${i+1}`,y.yearImage)}</div></div>`;}

function personalGoalsList(){return allWithOther(state.personalGoals,state.personalGoalsOther).filter(x=>x!=="I am not sure yet");}
function reviewOptions(goal){const val=state.personalGoalReview[goal]||"";return `<select data-review-goal="${esc(goal)}"><option value="">Choose one</option>${["Yes, I think I will have achieved this","I may still be working toward this","My goal may have changed","I am no longer sure I want this"].map(x=>`<option ${val===x?"selected":""}>${x}</option>`).join("")}</select>`;}

function renderReview(el){const goals=personalGoalsList();el.innerHTML=`<div class="review-grid"><aside><h3>Color style</h3>${[["professional","Professional"],["colorful","Colorful"],["vision","Vision Board"]].map(([v,t])=>`<div class="style-card ${state.style===v?"active":""}" data-style="${v}"><div class="style-preview preview-${v}">${t}</div><strong>${t}</strong><div class="theme-note">${v==="professional"?"Navy, orange, and clean lines":v==="colorful"?"Bright multi-color sections":"Purple, pink, and scrapbook style"}</div></div>`).join("")}<h3>PDF layout</h3>${[["compact","Compact Workbook","Recommended: less blank space"],["presentation","Presentation Pages","Larger text and more space"]].map(([v,t,d])=>`<div class="format-card ${state.outputLayout===v?"active":""}" data-layout="${v}"><strong>${t}</strong><div class="help">${d}</div></div>`).join("")}</aside><div><div class="review-editor"><h3>Personal Goals Check-In</h3><p class="section-intro">Think back to the personal goals you chose at the beginning. Where do you think you may be in five years?</p>${goals.length?`<div class="goal-review-list">${goals.map(g=>`<label><span>${esc(g)}</span>${reviewOptions(g)}</label>`).join("")}</div>`:`<p class="notice">No personal goals were selected at the beginning.</p>`}<div class="question">${writingBox("personalGoalReflection","Do you think you will have achieved any of your personal goals too? Explain.",["I think I will have achieved…","I may still be working toward…","My personal goals may change because…"],state.personalGoalReflection)}</div></div><h3 class="preview-heading">Preview My Plan</h3><div id="planPreview" class="plan-preview layout-${state.outputLayout}">${buildSlides()}</div><div class="review-actions"><button id="printBtn" class="primary">Print / Save PDF</button><button id="docxBtn" class="secondary">Download Word Document (.docx)</button><button id="htmlBtn" class="secondary">Download Viewable Web Plan</button><button id="textBtn" class="secondary">Download Plain Text</button><button id="dataBtn" class="secondary">Download Saved Answers</button></div><p class="notice">The Compact Workbook PDF keeps related information close together and uses less blank space.</p></div></div>`;
  el.querySelectorAll("[data-style]").forEach(x=>x.onclick=()=>{state.style=x.dataset.style;save(true);render();});
  el.querySelectorAll("[data-layout]").forEach(x=>x.onclick=()=>{state.outputLayout=x.dataset.layout;save(true);render();});
  el.querySelectorAll("[data-review-goal]").forEach(x=>x.onchange=()=>{state.personalGoalReview[x.dataset.reviewGoal]=x.value;save(true);});
  document.getElementById("printBtn").onclick=()=>window.print();
  document.getElementById("docxBtn").onclick=downloadDocx;
  document.getElementById("htmlBtn").onclick=downloadHtml;
  document.getElementById("textBtn").onclick=downloadText;
  document.getElementById("dataBtn").onclick=downloadData;
}

function p(v){return `<p>${esc(v||"Not answered yet.").replace(/\n/g,"<br>")}</p>`;}
function bullets(a){return a?.length?`<ul>${a.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:"<p>Not answered yet.</p>";}
function imageTag(src,cls="output-image"){return src?`<img class="${cls}" src="${src}" alt="Student-selected picture">`:"";}
function yearCard(title,text){return `<div class="output-card"><h3>${title}</h3>${p(text)}</div>`;}
function answerBlock(icon,title,text,tone="blue"){
  return `<div class="answer-block tone-${tone}"><div class="answer-icon">${icon}</div><div><h3>${esc(title)}</h3>${p(text)}</div></div>`;
}
function sectionBanner(icon,title,tone="blue"){
  return `<div class="section-banner tone-${tone}"><span>${icon}</span><h2>${esc(title)}</h2></div>`;
}
function goalListHtml(goals){return goals?.length?`<ul class="pretty-list">${goals.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:`<p>Not answered yet.</p>`;}
function buildSlides(){
  const cls=state.style, compact=state.outputLayout==="compact"?"compact-slide":"presentation-slide";
  const strengths=allWithOther(state.strengths,state.strengthsOther), growth=allWithOther(state.growth,state.growthOther), careers=allWithOther(state.careerAreas,state.careerAreasOther), training=state.trainingOther||state.training, help=allWithOther(state.trainingHelp,state.trainingHelpOther), goals=personalGoalsList();
  const grad=Number(state.gradYear||new Date().getFullYear());
  const journeyCards=state.years.map((y,i)=>`<div class="journey-card jc-${i+1}"><div class="journey-icon">${["🎓","📘","🤝","💼","🎯"][i]}</div><strong>Year ${i+1}</strong><span>${grad+i}</span><p>${esc(y.educationText||y.workText||y.personalGoalText||"My plan is still developing.")}</p></div>`).join("");
  const goalPreview=goals.slice(0,6).map(g=>`<li>${esc(g)}</li>`).join("");
  const years=state.years.map((y,i)=>`<section class="slide designed-slide ${cls} ${compact} year-output">
    ${sectionBanner(["🌱","🧰","🚀","🧭","⭐"][i],`Year ${i+1}: ${grad+i} - ${yearThemes[i][0]}`,["green","blue","purple","orange","red"][i])}
    <div class="year-intro">${imageTag(y.yearImage,"year-feature-image")}<div><p class="year-kicker">YEAR ${i+1} OF 5</p><h3>${esc(yearThemes[i][0])}</h3></div></div>
    <div class="designed-card-grid">${answerBlock("🎓","Education & Training",y.educationText,"green")}${answerBlock("💼","Employment",y.workText,"blue")}${answerBlock("💵","Money",y.moneyText,"orange")}${answerBlock("🏠","Living",y.livingText,"purple")}${answerBlock("🚌","Transportation",y.transportText,"blue")}${answerBlock("⚠","Possible Challenge",y.roadblockText,"red")}${answerBlock("✓","Possible Solution",y.solutionText,"green")}${answerBlock("♥","Personal Goal",y.personalGoalText,"purple")}</div>
    <div class="page-wave"></div></section>`).join("");
  return `<section class="slide designed-slide ${cls} ${compact} cover-slide-new">
    <div class="cover-ribbon"></div><div class="cover-main"><h1>My Five-Year Plan</h1><div class="star-divider"><span>★</span></div><h2>${esc(state.studentName||"Student Name")}</h2><p class="cover-grad-label">Expected Graduation Year</p><p class="cover-grad-year">${esc(state.gradYear||"")}</p>${imageTag(state.headshot,"cover-photo-new")}</div>
    <div class="mini-section-title"><span>⌖</span><h3>My Journey at a Glance</h3></div><div class="journey-cards">${journeyCards}</div>
    <div class="mini-section-title goals-title"><span>◎</span><h3>My Personal Goals in Five Years</h3></div><div class="cover-goals"><ul>${goalPreview||"<li>My goals are still developing.</li>"}</ul><p>${esc(state.personalGoalReflection||state.personalGoalsWhy||"")}</p></div><div class="page-wave"></div></section>
  <section class="slide designed-slide ${cls} ${compact}">${sectionBanner("★","My Dream","blue")}<div class="dream-layout"><div>${answerBlock("🎓","Work, School, or Training",state.visionWork,"green")}${answerBlock("⌂","Home and Daily Life",state.visionHome,"blue")}${answerBlock("$","Money",state.visionMoney,"green")}${answerBlock("★","What Success Means to Me",state.visionSuccess,"purple")}</div>${imageTag(state.dreamImage,"side-feature-image")}</div>${sectionBanner("●","Personal and Social Goals","purple")}<div class="wide-soft-card goals-card">${goalListHtml(goals)}<p>${esc(state.personalGoalsWhy||"")}</p></div>${sectionBanner("⬟","My Strengths & Growth","green")}<div class="two-feature-cards"><div class="wide-soft-card"><h3>My Strengths</h3>${goalListHtml(strengths)}<p>${esc(state.strengthExample||"")}</p></div><div class="wide-soft-card"><h3>Skills I Want to Improve</h3>${goalListHtml(growth)}<p>${esc(state.growthFirst||"")}</p></div></div><div class="page-wave"></div></section>
  <section class="slide designed-slide ${cls} ${compact}">${sectionBanner("◆","My Career & Training Plan","orange")}<div class="career-hero"><div><p class="career-label">Career I Want to Explore</p><h3>${esc(state.careerChoice||"My career goal is still developing.")}</h3><p>${esc(state.careerWhy||"")}</p></div>${imageTag(state.careerImage,"career-feature-image")}</div><div class="career-grid"><div class="wide-soft-card"><h3>Career Areas</h3>${goalListHtml(careers)}</div><div class="wide-soft-card"><h3>Education or Training</h3><p>${esc(training||"Not answered yet.")}</p></div><div class="wide-soft-card span-two"><h3>Help I May Need</h3>${goalListHtml(help)}</div></div><div class="page-wave"></div></section>${years}
  <section class="slide designed-slide ${cls} ${compact} final-journey">${sectionBanner("⌖","My Journey at a Glance","blue")}<div class="journey-cards large">${journeyCards}</div>${sectionBanner("◎","My Personal Goals in Five Years","orange")}<div class="goal-summary-designed">${goals.length?goals.map(g=>`<div><strong>${esc(g)}</strong><span>${esc(state.personalGoalReview[g]||"Not reviewed yet")}</span></div>`).join(""):`<p>No personal goals selected.</p>`}</div><div class="reflection-box"><h3>My Reflection</h3><p>${esc(state.personalGoalReflection||"Not answered yet.")}</p></div><div class="page-wave"></div></section>`;
}

function collect(){document.querySelectorAll("[data-field]").forEach(x=>{if(x.type==="radio"&&!x.checked)return;setPath(x.dataset.field,x.value);});document.querySelectorAll("[data-array]").forEach(x=>{const path=x.dataset.array;const group=[...document.querySelectorAll(`[data-array="${CSS.escape(path)}"]`)];setPath(path,group.filter(c=>c.checked).map(c=>c.value));});save(true);}
function bind(){document.querySelectorAll("[data-field]").forEach(x=>x.addEventListener("input",()=>{setPath(x.dataset.field,x.value);if(x.dataset.field==="studentName")document.getElementById("studentNameSide").value=x.value;save(true);}));document.querySelectorAll("[data-array]").forEach(x=>x.addEventListener("change",()=>{const path=x.dataset.array;const vals=[...document.querySelectorAll(`[data-array="${CSS.escape(path)}"]`)].filter(c=>c.checked).map(c=>c.value);if(path==="strengths"&&vals.length+(state.strengthsOther?1:0)>5){x.checked=false;flash("Please choose no more than five strengths.");return;}setPath(path,vals);save(true);if(path==="strengths")render();}));document.querySelectorAll("[data-image]").forEach(x=>{if(x.type!=="file")return;x.onchange=()=>{const f=x.files?.[0];if(!f)return;if(f.size>4_000_000){flash("Please choose a picture smaller than 4 MB.");return;}const r=new FileReader();r.onload=()=>{setPath(x.dataset.image,r.result);save(true);render();};r.readAsDataURL(f);};});document.querySelectorAll(".remove-image").forEach(x=>x.onclick=()=>{setPath(x.dataset.image,"");save(true);render();});}

function render(){renderNav();const def=stepDefs[currentStep],el=document.getElementById("content");document.getElementById("sectionLabel").textContent=`STEP ${currentStep+1} OF ${stepDefs.length}`;document.getElementById("sectionTitle").textContent=def.title;const pct=Math.round((currentStep/(stepDefs.length-1))*100);document.getElementById("progressText").textContent=`${pct}% complete`;document.getElementById("progressBar").style.width=`${pct}%`;document.getElementById("footerStep").textContent=`Step ${currentStep+1} of ${stepDefs.length} — ${def.label}`;document.getElementById("footerProgressText").textContent=`${pct}% complete`;document.getElementById("footerProgressBar").style.width=`${pct}%`;if(def.id==="welcome")renderWelcome(el);else if(def.id==="vision")renderVision(el);else if(def.id==="strengths")renderStrengths(el);else if(def.id==="career")renderCareer(el);else if(def.id.startsWith("year"))renderYear(el,Number(def.id.slice(4))-1);else renderReview(el);bind();document.getElementById("backBtn").disabled=currentStep===0;document.getElementById("nextBtn").textContent=currentStep===stepDefs.length-1?"Print / Save PDF":def.id==="year5"?"View My Finished Plan":"Next";document.getElementById("studentNameSide").value=state.studentName||"";window.scrollTo({top:0,behavior:"smooth"});}

function downloadBlob(content,type,name){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function fileBase(){return (state.studentName||"student").replace(/[^a-z0-9]+/gi,"_");}
function downloadText(){downloadBlob(planText(),"text/plain",`${fileBase()}_five_year_plan.txt`);}
function downloadData(){downloadBlob(JSON.stringify(state,null,2),"application/json",`${fileBase()}_saved_answers.json`);}
function downloadHtml(){const css=document.querySelector("link[rel=stylesheet]").href;const html=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(state.studentName)} Five-Year Plan</title><style>body{font-family:Arial;background:#eef2f7;margin:0}.toolbar{position:sticky;top:0;background:#1f2937;padding:12px;text-align:center}.toolbar button{padding:10px 18px}.plan-preview{max-width:900px;margin:20px auto}.slide{background:white;padding:28px;min-height:900px;margin-bottom:20px;page-break-after:always}.output-card-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.output-card{border:1px solid #ddd;border-radius:10px;padding:10px}.journey-timeline{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.journey-stop{border:1px solid #ddd;padding:10px;border-radius:10px}@media print{.toolbar{display:none}.slide{margin:0;box-shadow:none}@page{size:letter portrait;margin:.4in}}</style></head><body><div class="toolbar"><button onclick="print()">Print / Save PDF</button></div><div class="plan-preview">${buildSlides()}</div></body></html>`;downloadBlob(html,"text/html",`${fileBase()}_five_year_plan.html`);}
function planText(){let t=`MY FIVE-YEAR PLAN\n${state.studentName}\nGraduation year: ${state.gradYear}\n\nMY DREAM\n${state.visionWork}\n${state.visionHome}\n${state.visionMoney}\n${state.visionSuccess}\n\nPERSONAL GOALS\n- ${personalGoalsList().join("\n- ")}\n${state.personalGoalsWhy}\n\nSTRENGTHS\n- ${allWithOther(state.strengths,state.strengthsOther).join("\n- ")}\n${state.strengthExample}\n\nGROWTH\n- ${allWithOther(state.growth,state.growthOther).join("\n- ")}\n${state.growthFirst}\n\nCAREER & TRAINING\n${state.careerChoice}\n${state.careerWhy}\n${state.trainingOther||state.training}\n`;state.years.forEach((y,i)=>{t+=`\nYEAR ${i+1}\nEducation: ${y.educationText}\nEmployment: ${y.workText}\nMoney: ${y.moneyText}\nLiving: ${y.livingText}\nTransportation: ${y.transportText}\nChallenge: ${y.roadblockText}\nSolution: ${y.solutionText}\nPersonal Goal: ${y.personalGoalText}\n`;});t+=`\nMY JOURNEY AT A GLANCE\n${personalGoalsList().map(g=>`${g}: ${state.personalGoalReview[g]||"Not reviewed yet"}`).join("\n")}\n${state.personalGoalReflection}`;return t;}

async function downloadDocx(){
  if(typeof JSZip==="undefined"){flash("The Word download library did not load.");return;}
  collect(); flash("Building the designed Word document...");
  const zip=new JSZip(), rels=[], contentTypes=new Set(); let imageId=1;
  const xe=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[m]));
  const themes={professional:{navy:"10234A",blue:"174EA6",green:"15803D",purple:"7E22CE",orange:"EA580C",red:"DC2626",soft:"F5F8FC"},colorful:{navy:"172554",blue:"2563EB",green:"16A34A",purple:"9333EA",orange:"F97316",red:"EF4444",soft:"F8FAFC"},vision:{navy:"3B176B",blue:"7C3AED",green:"059669",purple:"DB2777",orange:"F59E0B",red:"E11D48",soft:"FAF5FF"}};
  const T=themes[state.style]||themes.professional;
  const run=(text,{bold=false,size=24,color="111827",italic=false}={})=>`<w:r><w:rPr>${bold?"<w:b/>":""}${italic?"<w:i/>":""}<w:color w:val="${color}"/><w:sz w:val="${size}"/><w:szCs w:val="${size}"/></w:rPr><w:t xml:space="preserve">${xe(text)}</w:t></w:r>`;
  const para=(text,opt={})=>`<w:p><w:pPr>${opt.align?`<w:jc w:val="${opt.align}"/>`:""}${opt.before||opt.after?`<w:spacing w:before="${opt.before||0}" w:after="${opt.after||0}"/>`:"<w:spacing w:after=\"90\"/>"}${opt.keep?"<w:keepNext/>":""}</w:pPr>${run(text,opt)}</w:p>`;
  const richPara=(runs,opt={})=>`<w:p><w:pPr>${opt.align?`<w:jc w:val="${opt.align}"/>`:""}<w:spacing w:after="${opt.after??80}"/>${opt.keep?"<w:keepNext/>":""}</w:pPr>${runs.join("")}</w:p>`;
  const pageBreak=()=>`<w:p><w:r><w:br w:type="page"/></w:r></w:p>`;
  const borders=(color="D7DEEA",sz=8)=>`<w:tcBorders><w:top w:val="single" w:sz="${sz}" w:color="${color}"/><w:left w:val="single" w:sz="${sz}" w:color="${color}"/><w:bottom w:val="single" w:sz="${sz}" w:color="${color}"/><w:right w:val="single" w:sz="${sz}" w:color="${color}"/></w:tcBorders>`;
  const cell=(content,{fill="FFFFFF",width=0,align="left",valign="center",borderColor="D7DEEA",margin=110}={})=>`<w:tc><w:tcPr>${width?`<w:tcW w:w="${width}" w:type="dxa"/>`:""}<w:shd w:val="clear" w:fill="${fill}"/>${borders(borderColor)}<w:vAlign w:val="${valign}"/><w:tcMar><w:top w:w="${margin}" w:type="dxa"/><w:left w:w="${margin}" w:type="dxa"/><w:bottom w:w="${margin}" w:type="dxa"/><w:right w:w="${margin}" w:type="dxa"/></w:tcMar></w:tcPr>${content}</w:tc>`;
  const table=(rows,widths=[],opt={})=>`<w:tbl><w:tblPr><w:tblW w:w="${opt.width||10800}" w:type="dxa"/><w:tblLayout w:type="fixed"/>${opt.noBorders?`<w:tblBorders><w:top w:val="nil"/><w:left w:val="nil"/><w:bottom w:val="nil"/><w:right w:val="nil"/><w:insideH w:val="nil"/><w:insideV w:val="nil"/></w:tblBorders>`:""}<w:tblCellMar><w:top w:w="40" w:type="dxa"/><w:left w:w="40" w:type="dxa"/><w:bottom w:w="40" w:type="dxa"/><w:right w:w="40" w:type="dxa"/></w:tblCellMar></w:tblPr>${widths.length?`<w:tblGrid>${widths.map(w=>`<w:gridCol w:w="${w}"/>`).join("")}</w:tblGrid>`:""}${rows.map(r=>`<w:tr>${r.join("")}</w:tr>`).join("")}</w:tbl>`;
  const banner=(title,color=T.blue,symbol="★")=>table([[cell(richPara([run(`${symbol}  `,{bold:true,size:28,color:"FFFFFF"}),run(title,{bold:true,size:28,color:"FFFFFF"})],{after:0}),{fill:color,width:10800,borderColor:color,margin:100})]],[10800],{width:10800});
  const bulletList=items=>(items?.length?items:["Not answered yet."]).map(x=>richPara([run("• ",{bold:true,color:T.orange}),run(x,{size:23})],{after:40})).join("");
  const answerRow=(title,text,color=T.blue,symbol="●")=>table([[cell(para(symbol,{bold:true,size:24,color,align:"center",after:0}),{fill:"F7FAFF",width:700,borderColor:"DDE5F0",align:"center"}),cell(richPara([run(title,{bold:true,size:24,color}),run("\n"+String(text||"Not answered yet."),{size:22,color:"111827"})],{after:0}),{fill:"FFFFFF",width:10100,borderColor:"DDE5F0"})]],[700,10100],{width:10800});
  async function imageSize(dataUrl){return new Promise(res=>{const im=new Image();im.onload=()=>res([im.naturalWidth||1,im.naturalHeight||1]);im.onerror=()=>res([1,1]);im.src=dataUrl;});}
  async function addImage(dataUrl,label,maxW=180,maxH=180,align="center"){
    if(!dataUrl||!/^data:image\//.test(dataUrl))return "";
    const m=dataUrl.match(/^data:image\/(png|jpeg|jpg|gif);base64,(.+)$/); if(!m)return "";
    let ext=m[1].toLowerCase();if(ext==="jpeg")ext="jpg";const rid=`rId${imageId}`,filename=`image${imageId}.${ext}`,id=imageId++;
    zip.folder("word").folder("media").file(filename,m[2],{base64:true});rels.push(`<Relationship Id="${rid}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/${filename}"/>`);contentTypes.add(ext);
    const [iw,ih]=await imageSize(dataUrl),scale=Math.min(maxW/iw,maxH/ih),w=Math.max(1,iw*scale),h=Math.max(1,ih*scale),cx=Math.round(w*9525),cy=Math.round(h*9525);
    return `<w:p><w:pPr><w:jc w:val="${align}"/><w:spacing w:after="100"/></w:pPr><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="${cx}" cy="${cy}"/><wp:docPr id="${id+20}" name="${xe(label)}"/><a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="0" name="${xe(filename)}"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="${rid}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>`;
  }
  const grad=Number(state.gradYear||new Date().getFullYear()),goals=personalGoalsList(),strengths=allWithOther(state.strengths,state.strengthsOther),growth=allWithOther(state.growth,state.growthOther),careers=allWithOther(state.careerAreas,state.careerAreasOther),help=allWithOther(state.trainingHelp,state.trainingHelpOther);
  let body="";
  body+=table([[cell("",{fill:T.orange,width:10800,borderColor:T.orange,margin:25})]],[10800]);
  body+=para("My Five-Year Plan",{bold:true,size:52,color:T.navy,align:"center",before:260,after:100});body+=para("★",{bold:true,size:25,color:T.orange,align:"center",after:70});body+=para(state.studentName||"Student Name",{bold:true,size:34,color:T.orange,align:"center",after:80});body+=para("EXPECTED GRADUATION YEAR",{bold:true,size:21,color:T.green,align:"center",after:20});body+=para(String(state.gradYear||""),{bold:true,size:54,color:T.green,align:"center",after:80});body+=await addImage(state.headshot,"Student headshot",190,190);
  body+=richPara([run("⌖  ",{bold:true,size:26,color:T.blue}),run("My Journey at a Glance",{bold:true,size:25,color:T.navy})],{after:60});
  const cardColors=["F1F8ED","EDF5FF","F7EFFB","FFF4E8","FFF0EF"],cardAccent=[T.green,T.blue,T.purple,T.orange,T.red];
  body+=table([state.years.map((y,i)=>cell(richPara([run(`Year ${i+1}\n`,{bold:true,size:21,color:cardAccent[i]}),run(`${grad+i}\n`,{bold:true,size:22,color:cardAccent[i]}),run(y.educationText||y.workText||y.personalGoalText||"My plan is still developing.",{size:19,color:"111827"})],{align:"center",after:0}),{fill:cardColors[i],width:2160,borderColor:cardAccent[i],align:"center",valign:"top",margin:90}))],[2160,2160,2160,2160,2160],{width:10800});
  body+=richPara([run("◎  ",{bold:true,size:26,color:T.orange}),run("My Personal Goals in Five Years",{bold:true,size:25,color:T.navy})],{after:60,before:100});
  body+=table([[cell(bulletList(goals.slice(0,Math.ceil(goals.length/2))),{fill:"FFF8F1",width:5400,borderColor:"FDBA74"}),cell(bulletList(goals.slice(Math.ceil(goals.length/2))),{fill:"FFF8F1",width:5400,borderColor:"FDBA74"})]],[5400,5400],{width:10800});
  body+=pageBreak();
  body+=banner("My Dream",T.blue,"★");
  const dreamImg=await addImage(state.dreamImage,"Dream image",150,150);
  body+=table([[cell(answerRow("Work, School, or Training",state.visionWork,T.green,"●")+answerRow("Home and Daily Life",state.visionHome,T.blue,"◆")+answerRow("Money",state.visionMoney,T.green,"$")+answerRow("What Success Means to Me",state.visionSuccess,T.purple,"★"),{width:8500,borderColor:"FFFFFF",margin:0}),cell(dreamImg||para("",{after:0}),{width:2300,borderColor:"FFFFFF",align:"center"})]],[8500,2300],{width:10800,noBorders:true});
  body+=banner("Personal and Social Goals",T.purple,"●");body+=table([[cell(bulletList(goals),{fill:"FAF5FF",width:10800,borderColor:"D8B4FE"})]],[10800]);body+=para(state.personalGoalsWhy||"",{size:22,color:"374151",after:100});
  body+=banner("My Strengths & Growth",T.green,"⬟");body+=table([[cell(para("My Strengths",{bold:true,size:23,color:T.green,after:50})+bulletList(strengths)+para(state.strengthExample||"",{size:21}),{fill:"F3FAEF",width:5400,borderColor:"B7D6A0",valign:"top"}),cell(para("Skills I Want to Improve",{bold:true,size:23,color:T.green,after:50})+bulletList(growth)+para(state.growthFirst||"",{size:21}),{fill:"F3FAEF",width:5400,borderColor:"B7D6A0",valign:"top"})]],[5400,5400],{width:10800});
  body+=pageBreak()+banner("My Career & Training Plan",T.orange,"◆");
  const careerImg=await addImage(state.careerImage,"Career image",170,170);
  body+=table([[cell(para("CAREER I WANT TO EXPLORE",{bold:true,size:19,color:T.orange,after:30})+para(state.careerChoice||"My career goal is still developing.",{bold:true,size:28,color:T.navy,after:70})+para(state.careerWhy||"",{size:22}),{fill:"FFF7ED",width:8200,borderColor:"FDBA74"}),cell(careerImg||para("",{after:0}),{fill:"FFF7ED",width:2600,borderColor:"FDBA74",align:"center"})]],[8200,2600],{width:10800});
  body+=table([[cell(para("Career Areas",{bold:true,size:23,color:T.blue})+bulletList(careers),{fill:"F7FAFF",width:5400,borderColor:"C7D7EE",valign:"top"}),cell(para("Education or Training",{bold:true,size:23,color:T.green})+para(state.trainingOther||state.training||"Not answered yet.",{size:22}),{fill:"F3FAEF",width:5400,borderColor:"B7D6A0",valign:"top"})],[cell(para("Help I May Need",{bold:true,size:23,color:T.purple})+bulletList(help),{fill:"FAF5FF",width:10800,borderColor:"D8B4FE",valign:"top"})]],[5400,5400],{width:10800});
  for(let i=0;i<5;i++){
    const y=state.years[i],color=cardAccent[i],symbol=["🌱","🧰","🚀","🧭","★"][i];body+=pageBreak()+banner(`Year ${i+1}: ${grad+i} - ${yearThemes[i][0]}`,color,symbol);
    const yi=await addImage(y.yearImage,`Year ${i+1} image`,125,110);
    body+=table([[cell(para(`YEAR ${i+1} OF 5`,{bold:true,size:19,color:"64748B",after:20})+para(yearThemes[i][0],{bold:true,size:30,color:T.navy,after:0}),{width:8300,borderColor:"FFFFFF"}),cell(yi||para("",{after:0}),{width:2500,borderColor:"FFFFFF",align:"center"})]],[8300,2500],{width:10800,noBorders:true});
    const entries=[["Education & Training",y.educationText,T.green,"●"],["Employment",y.workText,T.blue,"◆"],["Money",y.moneyText,T.orange,"$"],["Living",y.livingText,T.purple,"⌂"],["Transportation",y.transportText,T.blue,"→"],["Possible Challenge",y.roadblockText,T.red,"!"],["Possible Solution",y.solutionText,T.green,"✓"],["Personal Goal",y.personalGoalText,T.purple,"♥"]];
    for(let r=0;r<entries.length;r+=2)body+=table([[cell(answerRow(...entries[r]),{width:5400,borderColor:"FFFFFF",margin:0}),cell(answerRow(...entries[r+1]),{width:5400,borderColor:"FFFFFF",margin:0})]],[5400,5400],{width:10800,noBorders:true});
  }
  body+=pageBreak()+banner("My Journey at a Glance",T.blue,"⌖");body+=table([state.years.map((y,i)=>cell(richPara([run(`Year ${i+1}\n`,{bold:true,size:22,color:cardAccent[i]}),run(`${grad+i}\n`,{bold:true,size:22,color:cardAccent[i]}),run(y.educationText||y.workText||y.personalGoalText||"My plan is still developing.",{size:20})],{align:"center",after:0}),{fill:cardColors[i],width:2160,borderColor:cardAccent[i],align:"center",valign:"top"}))],[2160,2160,2160,2160,2160],{width:10800});body+=banner("My Personal Goals in Five Years",T.orange,"◎");
  const reviewRows=goals.length?goals.map(g=>[cell(para(g,{bold:true,size:19,color:T.navy,after:20})+para(state.personalGoalReview[g]||"Not reviewed yet",{size:21,color:"475569",after:0}),{fill:"FFFAF5",width:5400,borderColor:"FED7AA"})]):[[cell(para("No personal goals selected.",{size:20}),{width:10800})]];
  for(let i=0;i<reviewRows.length;i+=2)body+=table([[reviewRows[i][0],reviewRows[i+1]?.[0]||cell(para("",{after:0}),{fill:"FFFFFF",width:5400,borderColor:"FFFFFF"})]],[5400,5400],{width:10800});
  body+=table([[cell(para("My Reflection",{bold:true,size:24,color:T.orange,after:50})+para(state.personalGoalReflection||"Not answered yet.",{size:22}),{fill:"FFF7ED",width:10800,borderColor:T.orange})]],[10800]);
  const doc=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"><w:body>${body}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="500" w:right="600" w:bottom="500" w:left="600"/><w:cols w:space="720"/><w:docGrid w:linePitch="360"/></w:sectPr></w:body></w:document>`;
  const defs=[`<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>`,`<Default Extension="xml" ContentType="application/xml"/>`];contentTypes.forEach(ext=>defs.push(`<Default Extension="${ext}" ContentType="image/${ext==="jpg"?"jpeg":ext}"/>`));
  zip.file("[Content_Types].xml",`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">${defs.join("")}<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>`);
  zip.folder("_rels").file(".rels",`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`);
  zip.folder("word").file("document.xml",doc).file("styles.xml",`<?xml version="1.0" encoding="UTF-8"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Aptos" w:hAnsi="Aptos"/><w:sz w:val="24"/><w:color w:val="111827"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="80"/></w:pPr></w:pPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style></w:styles>`);
  zip.folder("word").folder("_rels").file("document.xml.rels",`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${rels.join("")}</Relationships>`);
  const blob=await zip.generateAsync({type:"blob",mimeType:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${fileBase()}_five_year_plan.docx`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200);flash("Designed Word document downloaded.");
}


document.getElementById("saveBtn").onclick=()=>{collect();save();};document.getElementById("resetBtn").onclick=()=>{if(confirm("Start over and erase all saved answers?")){localStorage.removeItem(STORAGE_KEY);location.reload();}};document.getElementById("backBtn").onclick=()=>{collect();if(currentStep>0){currentStep--;render();}};document.getElementById("nextBtn").onclick=()=>{collect();if(currentStep<stepDefs.length-1){currentStep++;render();}else window.print();};document.getElementById("studentNameSide").oninput=e=>{state.studentName=e.target.value;save(true);document.querySelector('[data-field="studentName"]')?.setAttribute("value",e.target.value);};
render();
